stages:
  - build
  - deploy

variables:
  IMAGE_NAME: your-django-app
  DOCKER_COMPOSE_FILE: docker-compose.yml

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .

deploy:
  stage: deploy
  script:
    - docker-compose -f $DOCKER_COMPOSE_FILE up -d
